import { expect, test } from '@playwright/test';
import { openAdminSection, openAuthenticatedAdmin } from './helpers';

test('the self-hosted Shop saves private digital products and offers owner Stripe settings', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 980 });
  await openAuthenticatedAdmin(page);
  await openAdminSection(page, 'Shop');
  const shop = page.locator('.orbitpage-selfhosted-shop');
  await expect(shop.locator('.shop-workspace')).toBeVisible();
  await expect(shop.getByRole('button', { name: 'Connect Stripe', exact: true })).toHaveCount(0);
  await shop.getByRole('button', { name: 'Add product', exact: true }).first().click();
  const editor = shop.locator('#shop-catalog');
  const title = `Synthetic OSS download ${Date.now()}`;
  await editor.getByLabel('Name', { exact: true }).fill(title);
  await editor.getByLabel('Full description', { exact: true }).fill('Synthetic digital delivery for the OSS browser test.');
  await editor.getByLabel('Price', { exact: true }).fill('10');
  await editor.getByRole('switch', { name: 'Available for purchase' }).click();
  await editor.getByRole('button', { name: 'Manage files' }).click();
  const files = page.getByRole('dialog', { name: 'Product files' });
  await files.getByLabel('Add files').setInputFiles({ name: 'synthetic.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.7\nsynthetic OSS browser fixture') });
  await files.getByRole('button', { name: 'Done', exact: true }).click();
  const saved = page.waitForResponse(response => response.url().endsWith('/api/shop/uploads/finalize'));
  await page.getByRole('group', { name: 'Unsaved Shop changes' }).getByRole('button', { name: 'Save', exact: true }).click();
  const dashboard = await (await saved).json();
  const product = dashboard.products.find((item: { title: string }) => item.title === title);
  expect(product.priceCents).toBe(1000);
  expect(product.files).toHaveLength(1);
  expect(product.files[0].id).toMatch(/^[a-f0-9]{64}$/);
  expect((await page.request.get(`/uploads/${product.files[0].id}`)).status()).toBe(404);
  await expect(page.getByRole('group', { name: 'Unsaved Shop changes' })).toBeHidden();
  await page.reload();
  await expect(shop.getByText(title, { exact: true }).first()).toBeVisible();
  await shop.getByRole('button', { name: 'Shop settings', exact: true }).click();
  await shop.getByRole('button', { name: 'Stripe', exact: true }).click();
  await expect(shop.getByLabel('Stripe secret API key')).toHaveAttribute('type', 'password');
  await expect(shop.getByLabel('Stripe webhook endpoint')).toHaveValue(/\/api\/shop\/webhook$/);
  await expect(shop.getByText(/no OrbitPage fee/)).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await shop.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  await page.goto('/shop/success');
  await expect(page.getByText(/Order|order/).first()).toBeVisible();
});
