import { forwardRef, type ForwardRefExoticComponent, type RefAttributes } from "react";
import type { SvgIconComponent } from "@mui/icons-material";
import type { SvgIconProps } from "@mui/material/SvgIcon";
import AccountCircleOutlined from "@mui/icons-material/AccountCircleOutlined";
import AccountTreeOutlined from "@mui/icons-material/AccountTreeOutlined";
import AddPhotoAlternateOutlined from "@mui/icons-material/AddPhotoAlternateOutlined";
import AddRounded from "@mui/icons-material/AddRounded";
import AdsClickOutlined from "@mui/icons-material/AdsClickOutlined";
import ArrowBackRounded from "@mui/icons-material/ArrowBackRounded";
import ArrowForwardRounded from "@mui/icons-material/ArrowForwardRounded";
import ArrowUpwardRounded from "@mui/icons-material/ArrowUpwardRounded";
import AssignmentTurnedInOutlined from "@mui/icons-material/AssignmentTurnedInOutlined";
import AutorenewRounded from "@mui/icons-material/AutorenewRounded";
import AutoAwesomeOutlined from "@mui/icons-material/AutoAwesomeOutlined";
import BarChartOutlined from "@mui/icons-material/BarChartOutlined";
import BusinessOutlined from "@mui/icons-material/BusinessOutlined";
import CheckCircleOutlineRounded from "@mui/icons-material/CheckCircleOutlineRounded";
import CheckRounded from "@mui/icons-material/CheckRounded";
import ChecklistRounded from "@mui/icons-material/ChecklistRounded";
import ChevronLeftRounded from "@mui/icons-material/ChevronLeftRounded";
import ChevronRightRounded from "@mui/icons-material/ChevronRightRounded";
import ConfirmationNumberOutlined from "@mui/icons-material/ConfirmationNumberOutlined";
import ContentCopyOutlined from "@mui/icons-material/ContentCopyOutlined";
import CodeOutlined from "@mui/icons-material/CodeOutlined";
import CookieOutlined from "@mui/icons-material/CookieOutlined";
import CreditCardOutlined from "@mui/icons-material/CreditCardOutlined";
import DeleteOutlineRounded from "@mui/icons-material/DeleteOutlineRounded";
import DescriptionOutlined from "@mui/icons-material/DescriptionOutlined";
import DownloadOutlined from "@mui/icons-material/DownloadOutlined";
import DragIndicatorRounded from "@mui/icons-material/DragIndicatorRounded";
import EditOutlined from "@mui/icons-material/EditOutlined";
import ErrorOutlineRounded from "@mui/icons-material/ErrorOutlineRounded";
import EventOutlined from "@mui/icons-material/EventOutlined";
import ExpandMoreRounded from "@mui/icons-material/ExpandMoreRounded";
import ExploreOutlined from "@mui/icons-material/ExploreOutlined";
import FolderCopyOutlined from "@mui/icons-material/FolderCopyOutlined";
import GppBadOutlined from "@mui/icons-material/GppBadOutlined";
import GridViewOutlined from "@mui/icons-material/GridViewOutlined";
import GroupOutlined from "@mui/icons-material/GroupOutlined";
import HelpOutlineRounded from "@mui/icons-material/HelpOutlineRounded";
import HomeOutlined from "@mui/icons-material/HomeOutlined";
import ImageOutlined from "@mui/icons-material/ImageOutlined";
import ImageSearchOutlined from "@mui/icons-material/ImageSearchOutlined";
import InsightsOutlined from "@mui/icons-material/InsightsOutlined";
import InfoOutlined from "@mui/icons-material/InfoOutlined";
import KeyOutlined from "@mui/icons-material/KeyOutlined";
import KeyboardDoubleArrowLeftRounded from "@mui/icons-material/KeyboardDoubleArrowLeftRounded";
import KeyboardDoubleArrowRightRounded from "@mui/icons-material/KeyboardDoubleArrowRightRounded";
import LanguageOutlined from "@mui/icons-material/LanguageOutlined";
import LinkOutlined from "@mui/icons-material/LinkOutlined";
import LocalOfferOutlined from "@mui/icons-material/LocalOfferOutlined";
import LockOutlined from "@mui/icons-material/LockOutlined";
import LogoutRounded from "@mui/icons-material/LogoutRounded";
import MailOutlineRounded from "@mui/icons-material/MailOutlineRounded";
import MenuRounded from "@mui/icons-material/MenuRounded";
import MapOutlined from "@mui/icons-material/MapOutlined";
import MonitorOutlined from "@mui/icons-material/MonitorOutlined";
import MovieOutlined from "@mui/icons-material/MovieOutlined";
import NoteAddOutlined from "@mui/icons-material/NoteAddOutlined";
import OpenInNewRounded from "@mui/icons-material/OpenInNewRounded";
import PaletteOutlined from "@mui/icons-material/PaletteOutlined";
import PlayArrowRounded from "@mui/icons-material/PlayArrowRounded";
import PersonAddAltOutlined from "@mui/icons-material/PersonAddAltOutlined";
import PersonOutlineRounded from "@mui/icons-material/PersonOutlineRounded";
import PowerSettingsNewRounded from "@mui/icons-material/PowerSettingsNewRounded";
import PublicOutlined from "@mui/icons-material/PublicOutlined";
import QrCode2Outlined from "@mui/icons-material/QrCode2Outlined";
import RedeemOutlined from "@mui/icons-material/RedeemOutlined";
import RefreshRounded from "@mui/icons-material/RefreshRounded";
import RemoveRounded from "@mui/icons-material/RemoveRounded";
import RestaurantMenuOutlined from "@mui/icons-material/RestaurantMenuOutlined";
import RestartAltRounded from "@mui/icons-material/RestartAltRounded";
import SaveOutlined from "@mui/icons-material/SaveOutlined";
import ScheduleOutlined from "@mui/icons-material/ScheduleOutlined";
import SearchRounded from "@mui/icons-material/SearchRounded";
import SendOutlined from "@mui/icons-material/SendOutlined";
import ShareOutlined from "@mui/icons-material/ShareOutlined";
import ShoppingBagOutlined from "@mui/icons-material/ShoppingBagOutlined";
import SmartphoneOutlined from "@mui/icons-material/SmartphoneOutlined";
import StorageOutlined from "@mui/icons-material/StorageOutlined";
import SupportAgentOutlined from "@mui/icons-material/SupportAgentOutlined";
import TextFieldsRounded from "@mui/icons-material/TextFieldsRounded";
import TrendingDownRounded from "@mui/icons-material/TrendingDownRounded";
import TrendingUpRounded from "@mui/icons-material/TrendingUpRounded";
import TuneRounded from "@mui/icons-material/TuneRounded";
import UploadOutlined from "@mui/icons-material/UploadOutlined";
import VerifiedUserOutlined from "@mui/icons-material/VerifiedUserOutlined";
import VisibilityOffOutlined from "@mui/icons-material/VisibilityOffOutlined";
import VisibilityOutlined from "@mui/icons-material/VisibilityOutlined";
import WalletOutlined from "@mui/icons-material/WalletOutlined";
import WarningAmberRounded from "@mui/icons-material/WarningAmberRounded";
import CloseRounded from "@mui/icons-material/CloseRounded";
import CropSquareOutlined from "@mui/icons-material/CropSquareOutlined";
import DashboardOutlined from "@mui/icons-material/DashboardOutlined";
import FormatListBulletedRounded from "@mui/icons-material/FormatListBulletedRounded";
import HistoryRounded from "@mui/icons-material/HistoryRounded";
import LayersOutlined from "@mui/icons-material/LayersOutlined";
import LocationOnOutlined from "@mui/icons-material/LocationOnOutlined";
import WorkOutlined from "@mui/icons-material/WorkOutlined";

export type MaterialIconProps = Omit<SvgIconProps, "color" | "fontSize"> & {
  absoluteStrokeWidth?: boolean;
  color?: string;
  size?: number | string;
  strokeWidth?: number;
};

export type MaterialIcon = ForwardRefExoticComponent<MaterialIconProps & RefAttributes<SVGSVGElement>>;

function createMaterialIcon(Icon: SvgIconComponent, displayName: string): MaterialIcon {
  const Component = forwardRef<SVGSVGElement, MaterialIconProps>(({
    absoluteStrokeWidth: _absoluteStrokeWidth,
    color,
    size = 24,
    strokeWidth: _strokeWidth,
    style,
    ...props
  }, ref) => (
    <Icon
      {...props}
      htmlColor={color}
      ref={ref}
      style={{ ...style, fontSize: typeof size === "number" ? `${size}px` : size }}
    />
  ));
  Component.displayName = displayName;
  return Component;
}

export const AlertTriangle = createMaterialIcon(WarningAmberRounded, "WarningAmberRounded");
export const AlertCircle = createMaterialIcon(ErrorOutlineRounded, "ErrorOutlineRounded");
export const Activity = createMaterialIcon(InsightsOutlined, "InsightsOutlined");
export const ArrowLeft = createMaterialIcon(ArrowBackRounded, "ArrowBackRounded");
export const ArrowRight = createMaterialIcon(ArrowForwardRounded, "ArrowForwardRounded");
export const ArrowUp = createMaterialIcon(ArrowUpwardRounded, "ArrowUpwardRounded");
export const ArrowDown = createMaterialIcon(ExpandMoreRounded, "ExpandMoreRounded");
export const BarChart2 = createMaterialIcon(BarChartOutlined, "BarChartOutlined");
export const BarChart3 = BarChart2;
export const Building2 = createMaterialIcon(BusinessOutlined, "BusinessOutlined");
export const BriefcaseBusiness = createMaterialIcon(WorkOutlined, "WorkOutlined");
export const CalendarClock = createMaterialIcon(EventOutlined, "EventOutlined");
export const Check = createMaterialIcon(CheckRounded, "CheckRounded");
export const CheckCircle2 = createMaterialIcon(CheckCircleOutlineRounded, "CheckCircleOutlineRounded");
export const CheckCircle = CheckCircle2;
export const ChevronDown = createMaterialIcon(ExpandMoreRounded, "ExpandMoreRounded");
export const ChevronLeft = createMaterialIcon(ChevronLeftRounded, "ChevronLeftRounded");
export const ChevronRight = createMaterialIcon(ChevronRightRounded, "ChevronRightRounded");
export const CircleUserRound = createMaterialIcon(AccountCircleOutlined, "AccountCircleOutlined");
export const Cookie = createMaterialIcon(CookieOutlined, "CookieOutlined");
export const Copy = createMaterialIcon(ContentCopyOutlined, "ContentCopyOutlined");
export const ClipboardCheck = createMaterialIcon(AssignmentTurnedInOutlined, "AssignmentTurnedInOutlined");
export const Code2 = createMaterialIcon(CodeOutlined, "CodeOutlined");
export const Compass = createMaterialIcon(ExploreOutlined, "ExploreOutlined");
export const CreditCard = createMaterialIcon(CreditCardOutlined, "CreditCardOutlined");
export const Database = createMaterialIcon(StorageOutlined, "StorageOutlined");
export const ExternalLink = createMaterialIcon(OpenInNewRounded, "OpenInNewRounded");
export const Download = createMaterialIcon(DownloadOutlined, "DownloadOutlined");
export const Edit = createMaterialIcon(EditOutlined, "EditOutlined");
export const Eye = createMaterialIcon(VisibilityOutlined, "VisibilityOutlined");
export const EyeOff = createMaterialIcon(VisibilityOffOutlined, "VisibilityOffOutlined");
export const FilePlus2 = createMaterialIcon(NoteAddOutlined, "NoteAddOutlined");
export const FileText = createMaterialIcon(DescriptionOutlined, "DescriptionOutlined");
export const Files = createMaterialIcon(FolderCopyOutlined, "FolderCopyOutlined");
export const Film = createMaterialIcon(MovieOutlined, "MovieOutlined");
export const Gift = createMaterialIcon(RedeemOutlined, "RedeemOutlined");
export const Globe2 = createMaterialIcon(PublicOutlined, "PublicOutlined");
export const GripVertical = createMaterialIcon(DragIndicatorRounded, "DragIndicatorRounded");
export const HelpCircle = createMaterialIcon(HelpOutlineRounded, "HelpOutlineRounded");
export const Home = createMaterialIcon(HomeOutlined, "HomeOutlined");
export const Info = createMaterialIcon(InfoOutlined, "InfoOutlined");
export const History = createMaterialIcon(HistoryRounded, "HistoryRounded");
export const Image = createMaterialIcon(ImageOutlined, "ImageOutlined");
export const ImagePlay = createMaterialIcon(ImageSearchOutlined, "ImageSearchOutlined");
export const ImagePlus = createMaterialIcon(AddPhotoAlternateOutlined, "AddPhotoAlternateOutlined");
export const ImageUp = ImagePlus;
export const KeyRound = createMaterialIcon(KeyOutlined, "KeyOutlined");
export const Languages = createMaterialIcon(LanguageOutlined, "LanguageOutlined");
export const LifeBuoy = createMaterialIcon(SupportAgentOutlined, "SupportAgentOutlined");
export const Link = createMaterialIcon(LinkOutlined, "LinkOutlined");
export const Link2 = Link;
export const Layout = createMaterialIcon(DashboardOutlined, "DashboardOutlined");
export const LayoutGrid = createMaterialIcon(GridViewOutlined, "GridViewOutlined");
export const LayoutTemplate = Layout;
export const Layers3 = createMaterialIcon(LayersOutlined, "LayersOutlined");
export const List = createMaterialIcon(FormatListBulletedRounded, "FormatListBulletedRounded");
export const ListChecks = createMaterialIcon(ChecklistRounded, "ChecklistRounded");
export const ListTree = createMaterialIcon(AccountTreeOutlined, "AccountTreeOutlined");
export const Loader2 = createMaterialIcon(AutorenewRounded, "AutorenewRounded");
export const LockKeyhole = createMaterialIcon(LockOutlined, "LockOutlined");
export const LogOut = createMaterialIcon(LogoutRounded, "LogoutRounded");
export const Mail = createMaterialIcon(MailOutlineRounded, "MailOutlineRounded");
export const Map = createMaterialIcon(MapOutlined, "MapOutlined");
export const MapPin = createMaterialIcon(LocationOnOutlined, "LocationOnOutlined");
export const Monitor = createMaterialIcon(MonitorOutlined, "MonitorOutlined");
export const Menu = createMaterialIcon(MenuRounded, "MenuRounded");
export const MousePointerClick = createMaterialIcon(AdsClickOutlined, "AdsClickOutlined");
export const Minus = createMaterialIcon(RemoveRounded, "RemoveRounded");
export const Palette = createMaterialIcon(PaletteOutlined, "PaletteOutlined");
export const PanelLeftClose = createMaterialIcon(KeyboardDoubleArrowLeftRounded, "KeyboardDoubleArrowLeftRounded");
export const PanelLeftOpen = createMaterialIcon(KeyboardDoubleArrowRightRounded, "KeyboardDoubleArrowRightRounded");
export const Power = createMaterialIcon(PowerSettingsNewRounded, "PowerSettingsNewRounded");
export const Play = createMaterialIcon(PlayArrowRounded, "PlayArrowRounded");
export const Plus = createMaterialIcon(AddRounded, "AddRounded");
export const QrCode = createMaterialIcon(QrCode2Outlined, "QrCode2Outlined");
export const RefreshCw = createMaterialIcon(RefreshRounded, "RefreshRounded");
export const RotateCcw = createMaterialIcon(RestartAltRounded, "RestartAltRounded");
export const Save = createMaterialIcon(SaveOutlined, "SaveOutlined");
export const Search = createMaterialIcon(SearchRounded, "SearchRounded");
export const Send = createMaterialIcon(SendOutlined, "SendOutlined");
export const Share2 = createMaterialIcon(ShareOutlined, "ShareOutlined");
export const ShieldAlert = createMaterialIcon(GppBadOutlined, "GppBadOutlined");
export const ShieldCheck = createMaterialIcon(VerifiedUserOutlined, "VerifiedUserOutlined");
export const ShoppingBag = createMaterialIcon(ShoppingBagOutlined, "ShoppingBagOutlined");
export const Sparkles = createMaterialIcon(AutoAwesomeOutlined, "AutoAwesomeOutlined");
export const Smartphone = createMaterialIcon(SmartphoneOutlined, "SmartphoneOutlined");
export const Sliders = createMaterialIcon(TuneRounded, "TuneRounded");
export const Square = createMaterialIcon(CropSquareOutlined, "CropSquareOutlined");
export const TicketCheck = createMaterialIcon(ConfirmationNumberOutlined, "ConfirmationNumberOutlined");
export const Trash2 = createMaterialIcon(DeleteOutlineRounded, "DeleteOutlineRounded");
export const Tag = createMaterialIcon(LocalOfferOutlined, "LocalOfferOutlined");
export const TrendingDown = createMaterialIcon(TrendingDownRounded, "TrendingDownRounded");
export const TrendingUp = createMaterialIcon(TrendingUpRounded, "TrendingUpRounded");
export const Type = createMaterialIcon(TextFieldsRounded, "TextFieldsRounded");
export const Upload = createMaterialIcon(UploadOutlined, "UploadOutlined");
export const User = createMaterialIcon(PersonOutlineRounded, "PersonOutlineRounded");
export const UserCircle2 = createMaterialIcon(AccountCircleOutlined, "AccountCircleOutlined");
export const UserPlus = createMaterialIcon(PersonAddAltOutlined, "PersonAddAltOutlined");
export const UserRound = User;
export const UsersRound = createMaterialIcon(GroupOutlined, "GroupOutlined");
export const UtensilsCrossed = createMaterialIcon(RestaurantMenuOutlined, "RestaurantMenuOutlined");
export const WalletCards = createMaterialIcon(WalletOutlined, "WalletOutlined");
export const X = createMaterialIcon(CloseRounded, "CloseRounded");
export const Clock3 = createMaterialIcon(ScheduleOutlined, "ScheduleOutlined");
